feat: userinfo with editing
Game-as-a-Service/Game-Lobby-Web pull request #126
Opened 2023-06-02 09:56 UTC by ttpss930141011

## Why need this change? / Root cause:

- As our per discussion, we will merge #61 and #62 as the UserInfoModal.

## Changes made:

- Added IO delay in request in pages\api\mock\users\me.ts
- Added editing function in core\lobby\components\UserInfoModal.tsx

## Test Scope / Change impact:

-

## Issue

- #104

2023-06-02 10:02 UTC, ttpss930141011 commented
寫得有點沒自信，想請問大家有沒有甚麼意見關於我的程式碼有哪邊可以改得更好。
@bxbdev 這邊小魔改了一下你的 UserInfoModal，有什麼意見請和我說。

2023-06-02 11:20 UTC, bxbdev commented
> 寫得有點沒自信，想請問大家有沒有甚麼意見關於我的程式碼有哪邊可以改得更好。 @bxbdev 這邊小魔改了一下你的 UserInfoModal，有任何建議請和我說。



@ttpss930141011  看過沒有什麼問題，有大佬處理很安心 XDDDD
補充一點，如果再補一個中文的長度驗證進去，會不會比較好？ 畢竟中文跟英文長度計算不一樣哦！

2023-06-04 07:00 UTC, JohnsonMao requested changes
辛苦了~再麻煩修改

2023-06-04 11:59 UTC, ttpss930141011 commented on components/shared/Sidebar.tsx
Sure! I've reverted the change.

2023-06-04 12:00 UTC, ttpss930141011 commented on components/lobby/UserInfoModal.tsx
> +                        readOnly={!editMode}
了解！一開始是用 readOnly 實作，忘記拿掉了。

2023-06-04 12:00 UTC, ttpss930141011 commented on components/lobby/UserInfoModal.tsx
> +                        readOnly={!editMode}
了解！一開始是用 readOnly 實作，忘記拿掉了。

2023-06-04 12:07 UTC, ttpss930141011 commented on components/shared/Sidebar.tsx
> > 寫得有點沒自信，想請問大家有沒有甚麼意見關於我的程式碼有哪邊可以改得更好。 @bxbdev 這邊小魔改了一下你的 UserInfoModal，有任何建議請和我說。
> 
> @ttpss930141011 看過沒有什麼問題，有大佬處理很安心 XDDDD 補充一點，如果再補一個中文的長度驗證進去，會不會比較好？ 畢竟中文跟英文長度計算不一樣哦！

已經上中文正則式判斷，感謝提醒！

2023-06-04 13:47 UTC, Parkerhiphop approved these changes

2023-06-05 03:23 UTC, JohnsonMao approved these changes

2023-06-05 04:31 UTC, merged