feat: layout
Game-as-a-Service/Game-Lobby-Web pull request #131
Opened 2023-06-04 09:04 UTC by bxbdev

## Why need this change? / Root cause:

- Added layout
- Added Chat componet

## Changes made:

-

## Test Scope / Change impact:

-

## Issue

- Closed #120

2023-06-06 05:10 UTC, ttpss930141011 commented on components/shared/Header.tsx
> +
我有寫一個 Badge component 哦，或是這邊有沒有其他考量呢？

2023-06-06 05:11 UTC, ttpss930141011 commented on components/shared/Header.tsx
> +    <span
我有寫一個 Badge component 哦，或是這邊有沒有其他考量呢？

2023-06-06 06:14 UTC, bxbdev commented on components/shared/Header.tsx
> +    <span
這個可以換成Badge，只是排版參考而已。

2023-06-06 12:45 UTC, bxbdev commented
@HongLinLiao Pagination已加入loading, isError, errorMessage的狀態，你看看有沒有問題？

2023-06-06 18:23 UTC, bxbdev commented
@JohnsonMao 看還有沒有缺少的部份，有缺再跟我說哦。

2023-06-09 12:09 UTC, bxbdev commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
@Parkerhiphop 因為參照原本的設計來看，Chat會是在header之外，而不是在header的裡面，然後為了不要header包一堆狀態，所以決定用Context的方式來寫入，去active不同的component。 這個還是 @HongLinLiao 的幫忙下，重構過後，最後的樣子。

*最後是最決，Chat不照設計師的方式和main在同一個水平上，而是直接採用fixed，固定在右側並蓋住內容。

2023-06-09 12:31 UTC, Parkerhiphop commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
header 包一堆狀態是正常的，把它抽到 Context 讓 Header 才需要觸發的狀態污染到全域比較不正常。

另外我有進去測過，把 Context 拔掉，狀態管理全部收進去 Header 的話，Chat 還是可以正常運作，畢竟他是會蓋住內容，未來如果採用 Portal 的方式，那就更不需要 Context 了。

Context 主要的用法是「避免 Props drilling」、「Cross Components State」、「Cooperate with Third party libs」，現在看來 Header 要觸發 Chat、UserInfoModal 和其他 Button 都沒有上述三種情境。

2023-06-09 12:35 UTC, bxbdev commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
@Parkerhiphop 讓大家投票決定一下，怎麼處理header的問題。 這方面還需要大家的幫忙。

2023-06-09 12:50 UTC, ttpss930141011 commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
Hi @bxbdev，這邊看了一下有兩個地方用到 UiContext：
- `components/shared/Chat/index.tsx` 
-  `components/shared/Header.tsx`

Chat component 已經直接包在 Provider 中所以不考慮，目前的確只需要包在 Header 外層就好。

2023-06-09 14:37 UTC, Parkerhiphop commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
其實 UI Provider 可以拆掉，直接把檔案都放在 `AppLayout` 就好

```
      {children}
      {openProfile && (
        <UserInfoModal
          isOpen={openProfile}
          onClose={() => setOpenProfile(false)}
        />
      )}
      <Chat />

2023-06-09 17:13 UTC, HongLinLiao commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
@bxbdev @Parkerhiphop  不是因為header裡面不想存在狀態這個原因才這樣包拉個context，而是如果我把傳遞props這個行為放到appLayout,後面所有有新的layout要用這種狀態元件都要自己重新建立狀態後丟進元件內，會增加layout的複雜性，當這個狀態未來邏輯更加複雜需要與其他狀態連動調整時會更難維護這段code。可以斟酌一下，要拆到header內也是沒問題的，感謝～

2023-06-10 02:19 UTC, Parkerhiphop commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
@HongLinLiao 

感謝補充脈絡！

不過我個人還是傾向於直接寫在 Header 裡，基於以下原因：
1. 關注點分離
   - 狀態管理的邏輯被封裝在單一元件內，降低了其他元件的認知負擔
   - 這種單純做條件渲染的狀態，未來如果有其他情境我也傾向在用的地方自己維護一個，畢竟 Layout 一般來說也不會太多
2. 可讀性與複雜度：
   - 將狀態集中在 Header 元件內，我直接看下來的狀態流比較直觀，不用再去看 Context 增加其他認知負擔，有新成員加入也不用去想像 Context 只有一個地方用到為什麼要抽出來
3. 過早最佳化
   - 回應到上一點，因為現在還不確定其他 Layout 的情形，所以純看程式碼會需要知道當初設計的人是多想這一層才拆的
   - 另外就是畫面不確定的話（是沒有 Header、還是有 Header 但保留其中一兩個等等），現在拆 Provider 之後要改 Provider 的機率也很高，我傾向等到那個情境出來我們再來抽
4. 封裝性
   - 如果Header的狀態被放在Context中，那麼任何可以接觸到這個Context的元件都可能改變這些狀態。
   - 這可能會帶來一些未預期的行為或者錯誤，降低可維護性。
   - 舉例來說，我可以在 Main 或 Footer 等有包在 AppLayout 的地方（像是 room ）去改變到 Header 的狀態
   
以上是我個人的想法，我有直接開一個 PR 可以看看我的版本：https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/156

如果想要沿用原本的做法的話，我會建議至少要改一下 `Context` 的名字，可以叫 `HeaderContext` 比較好， `UIContext` 可能指涉的 Scope 會太大。

cc @bxbdev @ttpss930141011 @JohnsonMao

2023-06-10 12:20 UTC, JohnsonMao commented on containers/layout/AppLayout.tsx
> +    <UiProvider>
我也同意把狀態存在 header 裡
而聊天室也同意使用 Portal 並用 fixed 的方式掛在畫面上
聊天室的部分可能要跟設計師溝通一下

2023-06-10 14:26 UTC, Parkerhiphop approved these changes

2023-06-10 15:26 UTC, JohnsonMao requested changes

2023-06-10 15:26 UTC, JohnsonMao commented on components/rooms/RoomCard.tsx
>  import { useState } from "react";
好像沒使用到 useState，可以移除

2023-06-10 16:44 UTC, JohnsonMao commented on components/rooms/RoomCard.tsx
>  import { useState } from "react";
我明天再調整一下～

2023-06-10 16:45 UTC, JohnsonMao approved these changes

2023-06-11 03:45 UTC, merged