[WIP]feat: private room component
Game-as-a-Service/Game-Lobby-Web pull request #153
Opened 2023-06-08 20:07 UTC by ttpss930141011

## Why need this change? / Root cause:

- The "Private Room" component needed to be extracted from the `components\lobby\CreateRoomModal` due to cluttered logic and the potential for future use in other scenarios.

![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/76243caf-f6a8-4453-8a1c-f14bcd1cafa1)

## Changes made:

- Added new shared component `PrivateRoom`.
- Added the storybook and test of `PrivateRoom`.
- Refactored the `CreateRoomModal.tsx` to extract private room logic.

## Test Scope / Change impact:

-

## Issue

- #150

2023-06-09 00:49 UTC, Yuwen-ctw commented
Hello Justin,
這份 PR 你將 CreateRoomModal 中的密碼輸入框抽取成 PrivateRoom 元件，同時新增其 storybook，看完後有兩個想法及一個議題想討論：
- 想法
1. 此元件的功能是讓使用者選擇建立或加入私有房間時，可以進行密碼的輸入；而此元件的命名目前以 Room 結尾，個人想法是覺得不太明確，以我自己的習慣，可能會用 PasswordInputs、PasswordField 等來命名，不過以上參考即可。

2. 此元件有一個 isPrivateRoomActive 函式，當此元件的 prop 的 active 為真時，透過此函式可以立即 focus 從左邊算起第一個尚未輸入的密碼輸入框，用以提升UX；不過目前的命名以 is 開頭，讓我剛開始看程式碼時，會預期他是一個布林值，或者是一個會依據條件回傳布林值的函式，但看完後才發現它其實是一個變更狀態的行為，且不會回傳任何值，因此會有一點困惑。若以我的習慣，可能會使用類似 setInputFocus 來命名。
近期在開發時，當不確定某個變數或函式可以如何命名時，我會問 chatgpt ，它給的答案我都挺滿意的，供參考。

- 議題
想跟大家討論的是，在這個專案中，什麼樣的元件是需要加入 storybook 的？
自己原本預期是所有 Spring 1 所列的元件才需要加入，因此後來在寫聊天室時，針對自定義的 ChatMessage 元件就沒有寫 storybook；不過現在若 PrivateRoom 有加入的話，是不是後續也再將 ChatMessage 加入呢 ?

以上，謝謝。

2023-06-09 01:18 UTC, Yuwen-ctw approved these changes

2023-06-09 02:18 UTC, JohnsonMao commented
我同意 @Yuwen-ctw 所說的
原本想的是把 Password component (那四個 input 輸入框與他對應的使用者操作邏輯) 封裝成 PasswordField
這樣未來除了密碼外，說不定驗證甚麼的也可以重複使用此 component

以下是我個人的想法，
只有 shared 下面的 component 才需要使用 storybook
我的理解是 storybook 主要展現 component 的各種狀態
而有特定商業邏輯的 component (例如: `lobby` 或 `rooms` 下面的) 則不需要 storybook

2023-06-09 02:23 UTC, JohnsonMao requested changes
感覺可以改成 PasswordField 這個命名
這樣這個 component 就不侷限在 密碼房 了

2023-06-09 02:23 UTC, JohnsonMao commented on components/shared/PrivateRoom/PrivateRoom.tsx
> +  const isPrivateRoomActive = () => {
```tsx
  const isPrivateRoomActive = () => {
    if (active && passwordValues.every((password) => password === "")) {
      handlePasswordFocus(0);
    }
    if (active && passwordValues.some((password) => password !== "")) {
      const index = passwordValues.findIndex((password) => password === "");
      handlePasswordFocus(index);
    }
    if (active && passwordValues.every((password) => password !== "")) {
      handlePasswordFocus(3);
    }
  };
```
這部分是不是可以簡化成
```tsx
  const handleInputFocus  = () => {
    if (active) {
      const index = passwordValues.findIndex((password) => password === "");

      handlePasswordFocus(index);
    }
  };
```

2023-06-09 04:52 UTC, ttpss930141011 commented
> Hello Justin, 這份 PR 你將 CreateRoomModal 中的密碼輸入框抽取成 PrivateRoom 元件，同時新增其 storybook，看完後有兩個想法及一個議題想討論：
> 
> * 想法
> 
> 1. 此元件的功能是讓使用者選擇建立或加入私有房間時，可以進行密碼的輸入；而此元件的命名目前以 Room 結尾，個人想法是覺得不太明確，以我自己的習慣，可能會用 PasswordInputs、PasswordField 等來命名，不過以上參考即可。
> 2. 此元件有一個 isPrivateRoomActive 函式，當此元件的 prop 的 active 為真時，透過此函式可以立即 focus 從左邊算起第一個尚未輸入的密碼輸入框，用以提升UX；不過目前的命名以 is 開頭，讓我剛開始看程式碼時，會預期他是一個布林值，或者是一個會依據條件回傳布林值的函式，但看完後才發現它其實是一個變更狀態的行為，且不會回傳任何值，因此會有一點困惑。若以我的習慣，可能會使用類似 setInputFocus 來命名。
>    近期在開發時，當不確定某個變數或函式可以如何命名時，我會問 chatgpt ，它給的答案我都挺滿意的，供參考。
> 
> * 議題
>   想跟大家討論的是，在這個專案中，什麼樣的元件是需要加入 storybook 的？
>   自己原本預期是所有 Spring 1 所列的元件才需要加入，因此後來在寫聊天室時，針對自定義的 ChatMessage 元件就沒有寫 storybook；不過現在若 PrivateRoom 有加入的話，是不是後續也再將 ChatMessage 加入呢 ?
> 
> 以上，謝謝。

Thank for you point out the problem! My code do have some ill-considered place.

After considering, I will make some small revisions like as following:
- Rename the `PrivateRoom` to `PasswordField`.
-  Rename the `isPrivateRoomActive` function to `setFocusedPasswordField`.
- Refactor the `setFocusedPasswordField` function that Mao mentioned before.

2023-06-09 05:05 UTC, ttpss930141011 commented on components/shared/PrivateRoom/PrivateRoom.tsx
> +  const isPrivateRoomActive = () => {
I have revised it. Thank for your suggestions!

2023-06-09 13:12 UTC, Yuwen-ctw approved these changes

2023-06-10 13:21 UTC, JohnsonMao approved these changes

2023-06-10 14:27 UTC, JohnsonMao requested changes

2023-06-10 14:27 UTC, JohnsonMao commented on components/shared/PasswordField/PasswordField.tsx
> +  const isNumeric = (value: string) => !/[\D]/.test(value);
`!/[\D]/.test(value)` 這裡可以改成 `/[\d]/.test(value)` 這樣可以更直觀

2023-06-10 14:27 UTC, JohnsonMao commented on components/shared/PasswordField/PasswordField.tsx
> +      私人房間
不好意思當初漏看這裡
```tsx
私人房間
<div className="text-sm mt-[14px] flex flex-col">
  <span>請輸入此房間密碼</span>
</div>
```
這個部分可以使用 props 來傳遞嗎
讓使用 component 的人可以決定 PasswordField 的 header 要放甚麼，也更加靈活

2023-06-10 15:02 UTC, ttpss930141011 commented on components/shared/PasswordField/PasswordField.tsx
> +  const isNumeric = (value: string) => !/[\D]/.test(value);
感謝！已修改，看好細XD

2023-06-10 15:03 UTC, ttpss930141011 commented on components/shared/PasswordField/PasswordField.tsx
> +      私人房間
這部分已經將私人房間的部分改用 `title` 傳入，請輸入此房間密碼則用 `subTitle` 傳入，感謝！

2023-06-11 06:52 UTC, Parkerhiphop commented
> Hello Justin, 這份 PR 你將 CreateRoomModal 中的密碼輸入框抽取成 PrivateRoom 元件，同時新增其 storybook，看完後有兩個想法及一個議題想討論：
> 
> * 想法
> 
> 1. 此元件的功能是讓使用者選擇建立或加入私有房間時，可以進行密碼的輸入；而此元件的命名目前以 Room 結尾，個人想法是覺得不太明確，以我自己的習慣，可能會用 PasswordInputs、PasswordField 等來命名，不過以上參考即可。
> 2. 此元件有一個 isPrivateRoomActive 函式，當此元件的 prop 的 active 為真時，透過此函式可以立即 focus 從左邊算起第一個尚未輸入的密碼輸入框，用以提升UX；不過目前的命名以 is 開頭，讓我剛開始看程式碼時，會預期他是一個布林值，或者是一個會依據條件回傳布林值的函式，但看完後才發現它其實是一個變更狀態的行為，且不會回傳任何值，因此會有一點困惑。若以我的習慣，可能會使用類似 setInputFocus 來命名。
>    近期在開發時，當不確定某個變數或函式可以如何命名時，我會問 chatgpt ，它給的答案我都挺滿意的，供參考。
> 
> * 議題
>   想跟大家討論的是，在這個專案中，什麼樣的元件是需要加入 storybook 的？
>   自己原本預期是所有 Spring 1 所列的元件才需要加入，因此後來在寫聊天室時，針對自定義的 ChatMessage 元件就沒有寫 storybook；不過現在若 PrivateRoom 有加入的話，是不是後續也再將 ChatMessage 加入呢 ?
> 
> 以上，謝謝。

基本上我們專案中有用到，並且在各大 UI Component Library 也都有列的基本元件一定會放進去，以 Atomic Design 的概念來說，就是 Atomic / Molecules 這個範圍內的會放進去。

不過我們畢竟不是在做 UI Component Library，因此如果有多頁面共用的元件，為了方便未來要用到的人參考，也可以考慮放進去，但是不用寫得太詳細，並且把分類（meta.title） 寫清楚就好，這邊都是 room 會用到的話，可以分類到 `Room/password`

有些東西不用這麼快地做得很泛用，避免過早最佳化哈哈

![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/45290853/7812e217-c40c-4bbb-9dd5-11e0732284ac)

cc @ttpss930141011 @Yuwen-ctw @JohnsonMao

2023-06-11 06:54 UTC, Parkerhiphop commented on components/shared/PasswordField/PasswordField.stories.tsx
> +  title: "Shared/PasswordField",
建議可改成 `Room/PasswordField` ，其他人開 Storybook 想參考時可以更快早到，未來也可能會有其他層級的共用元件，如果都塞在 Shared/ 底下會越來越難找

2023-06-11 07:38 UTC, JohnsonMao commented
> > Hello Justin, 這份 PR 你將 CreateRoomModal 中的密碼輸入框抽取成 PrivateRoom 元件，同時新增其 storybook，看完後有兩個想法及一個議題想討論：
> > 
> > * 想法
> > 
> > 
> > 1. 此元件的功能是讓使用者選擇建立或加入私有房間時，可以進行密碼的輸入；而此元件的命名目前以 Room 結尾，個人想法是覺得不太明確，以我自己的習慣，可能會用 PasswordInputs、PasswordField 等來命名，不過以上參考即可。
> > 2. 此元件有一個 isPrivateRoomActive 函式，當此元件的 prop 的 active 為真時，透過此函式可以立即 focus 從左邊算起第一個尚未輸入的密碼輸入框，用以提升UX；不過目前的命名以 is 開頭，讓我剛開始看程式碼時，會預期他是一個布林值，或者是一個會依據條件回傳布林值的函式，但看完後才發現它其實是一個變更狀態的行為，且不會回傳任何值，因此會有一點困惑。若以我的習慣，可能會使用類似 setInputFocus 來命名。
> >    近期在開發時，當不確定某個變數或函式可以如何命名時，我會問 chatgpt ，它給的答案我都挺滿意的，供參考。
> > 
> > 
> > * 議題
> >   想跟大家討論的是，在這個專案中，什麼樣的元件是需要加入 storybook 的？
> >   自己原本預期是所有 Spring 1 所列的元件才需要加入，因此後來在寫聊天室時，針對自定義的 ChatMessage 元件就沒有寫 storybook；不過現在若 PrivateRoom 有加入的話，是不是後續也再將 ChatMessage 加入呢 ?
> > 
> > 以上，謝謝。
> 
> 基本上我們專案中有用到，並且在各大 UI Component Library 也都有列的基本元件一定會放進去，以 Atomic Design 的概念來說，就是 Atomic / Molecules 這個範圍內的會放進去。
> 
> 不過我們畢竟不是在做 UI Component Library，因此如果有多頁面共用的元件，為了方便未來要用到的人參考，也可以考慮放進去，但是不用寫得太詳細，並且把分類（meta.title） 寫清楚就好，這邊都是 room 會用到的話，可以分類到 `Room/password`
> 
> 有些東西不用這麼快地做得很泛用，避免過早最佳化哈哈
> 
> ![image](https://user-images.githubusercontent.com/45290853/244918686-7812e217-c40c-4bbb-9dd5-11e0732284ac.png)
> 
> 另外元件分類可參考：https://ithelp.ithome.com.tw/articles/10268340
> 
> cc @ttpss930141011 @Yuwen-ctw @JohnsonMao

我同意~只是我好懶~想直接用他的 Password field XDDD
不想複製貼上到我的進入密碼房 Modal

2023-06-11 08:18 UTC, JohnsonMao approved these changes

2023-06-11 08:37 UTC, ttpss930141011 commented on components/shared/PasswordField/PasswordField.stories.tsx
> +  title: "Shared/PasswordField",
已改為`Room/PasswordField`。

2023-06-14 12:58 UTC, merged