[WIP]feat: carousel
Game-as-a-Service/Game-Lobby-Web pull request #160
Opened 2023-06-10 14:52 UTC by pcshen0828

## Why need this change? / Root cause:

-

## Changes made:

-

## Test Scope / Change impact:

-

## Issue

-

2023-06-14 07:48 UTC, JohnsonMao requested changes
因為組件有點大，目前先提出這些問題

2023-06-14 07:48 UTC, JohnsonMao commented on components/shared/Carousel/Carousel.tsx
> +  }, [carouselItemsContainerRef.current, carouselItemsRef.current]);
`useEffect` 的依賴使用 `ref.current` 是不安全的作法
因為實際 ref 變動並不會觸發組件更新渲染

詳細可以看: https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom

2023-06-15 14:56 UTC, Yuwen-ctw commented on components/shared/Carousel/Carousel.tsx
> +          return payload < 0 || payload < translateValuePerSlide ? 0 : payload;
這一段程式碼，是判斷下一次往左輪播時，其 translateValue 是否為負值或者小於每次輪播時所需要的長度，若是則輪播至最左側，若否則依照計算結果進行輪播。

而觀察此 Function component 的開頭有針對 props 的 itemsWidth 及 itemsToSlide  進行是否為正值的檢查，且後續 applyTranslateValuePerSlide 函式的計算結果亦恆為正值，因此 Line 195 中 payload < 0 的判斷似乎是可省略的判斷式 （只要小於零，則必定小於 translateValuePerSlide ）；同理，Line 201 的 payload > maxTranslateValue 也是同樣的情形，payload 若超過 maxTranslateValue ，則 maxTranslateValue - payload 必定為負值，因此必小於 translateValuePerSlide，也是可能可省略的語法。不過以上是個人看法，維持原貌也許可讓閱讀者更容易理解。

最後，在閱讀的過程中，payload 這一個變數名稱，讓個人在看完這一小段程式碼之前較難猜出其含意，看完後可以明白其實是代表「新的 translateValue」、「理論上的 translateValue」或「初步計算的 translateValue」，若以個人想法，可能會以 newTranslateValue 進行命名。

以上說明，謝謝！

2023-06-16 01:36 UTC, pcshen0828 commented on components/shared/Carousel/Carousel.tsx
> +  }, [carouselItemsContainerRef.current, carouselItemsRef.current]);
感謝分享，後來發現不影響功能，已移除 `useEffect` 中的 `ref.current` 依賴

2023-06-16 01:38 UTC, pcshen0828 commented on package.json
> +    "storybook-addon-next": "^1.8.0",
已解除安裝，但為了解決 storybook 的 svg 渲染問題，我參考了[這篇](https://github.com/storybookjs/storybook/issues/18557#issuecomment-1426150038)，在 storybook `main.ts` 新增了 `webpackFinal` config

2023-06-16 01:39 UTC, pcshen0828 commented on components/shared/Carousel/Carousel.tsx
> +      setMaskedItemIndex(_maskedItemIndex);
感謝建議，已修改

2023-06-16 01:40 UTC, pcshen0828 commented on components/shared/Carousel/Carousel.tsx
> +          return payload < 0 || payload < translateValuePerSlide ? 0 : payload;
感謝建議，已移除多餘的判斷邏輯，並將 `payload` 命名更改為 `newTranslateValue`

2023-06-16 02:15 UTC, JohnsonMao commented on package.json
> +    "storybook-addon-next": "^1.8.0",
很巧的是~我 `refactor/icon` 這個 [PR](https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/172/files) 也有添加類似的東西，感覺到時候 merge 到主分支會衝突

2023-06-16 12:13 UTC, Yuwen-ctw approved these changes

2023-06-16 13:29 UTC, pcshen0828 commented on package.json
> +    "storybook-addon-next": "^1.8.0",
我可以同步你的 config~ 但會有影響的是：因為 `icon: true` 會把 svg 的 width 和 height 設為 `1em`，所以其他元件如果有用固定寬高的 svg（如 `CarouselArrowButton` 裡面的 arrow ），在 storybook 裡面的大小看起來可能會和實際不同~

2023-06-17 22:56 UTC, pcshen0828 commented on package.json
> +    "storybook-addon-next": "^1.8.0",
done

2023-06-18 06:04 UTC, JohnsonMao approved these changes

2023-06-20 09:16 UTC, merged