Fix/private selected
Game-as-a-Service/Game-Lobby-Web pull request #231
Opened 2023-07-07 14:22 UTC by arealclimber

## Why need this change? / Root cause:

- Clicking the password when creating a room should select the private room immediately

## Changes made:
component:

- PasswordField 
- CreateRoomModal

## Test Scope / Change impact:

-

## Issue

- #230

2023-07-13 13:48 UTC, JohnsonMao requested changes
改完應該就 OK 了~

2023-07-13 13:48 UTC, JohnsonMao commented on components/shared/PasswordField/PasswordField.tsx
> +  getPasswordSelected?: (bool: boolean) => void;
`getPasswordSelected` 這個部分能幫我改成 `onInputClick?: (e: event) => void`
這樣比較泛用
下面就改成 `onInputClick && onInputClick(event);` 就可以了

2023-07-13 13:48 UTC, JohnsonMao commented on components/lobby/CreateRoomModal/CreateRoomModal.tsx
> +    setIsPublic(!bool);
然後這裡就可以改成 `setIsPublic(false)` 了
因為點密碼的 input 框就代表他選了私人房

2023-07-17 14:00 UTC, arealclimber commented on components/shared/PasswordField/PasswordField.tsx
> +  getPasswordSelected?: (bool: boolean) => void;
已修正，請查看

2023-07-17 14:00 UTC, arealclimber commented on components/lobby/CreateRoomModal/CreateRoomModal.tsx
> +    setIsPublic(!bool);
已修正，請查看

2023-07-17 14:35 UTC, JohnsonMao approved these changes

2023-07-18 09:51 UTC, Yuwen-ctw approved these changes

2023-07-19 14:24 UTC, merged