feat: room status
Game-as-a-Service/Game-Lobby-Web pull request #273
Opened 2023-08-13 15:17 UTC by bxbdev

## Why need this change? / Root cause:

- Added events from socket 

## Changes made:

-

## Test Scope / Change impact:

-

## Issue

-

2023-08-14 03:11 UTC, bxbdev commented
@Yuwen-ctw 我是覺得 roomId 還是保持原本就好，不用需要特別改成 message.to ，這樣反而會看不懂這個 message.to 的用意。
然後原本  socket?.  的寫法，是因為我的 VS Code 會抱怨，是否能確認一下在 socket 運作之前，確保 socket 是找的到的？

2023-08-14 05:05 UTC, Yuwen-ctw commented
Hello bxb,

先說明一個前提是，依現行主線的程式碼，透過聊天室發送訊息時，其型別已事先定義於 `components/rooms/RoomChatroom/index.ts` 裡面了，如下圖所示:
![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/114204927/b6ca2369-f994-4f12-8efa-74653a87188c)
因此在前端透過聊天室發送訊息時，後端接到的資料 (socket.on 的第二個參數，`pages/api/mock/socketio.ts` Line 40)，其實就是 MessageType，因此再回傳給前端時，可以透過 message.to 取得 MessageType 中 to 的屬性。

所以，不確定你對於 message.to 的想法是針對 MessageType 中的 to 屬性，還是針對 mock socket server 的使用方法呢?

假如是前者，那型別完全是可以進行調整的：
先前定義聊天訊息的型別（MessageType）時，針對接收訊息對象的 key 到底該如何命名我也思考了許久，之所以沒有選擇使用 roomId，是因為考慮未來聊天訊息可能不只發生在房間內，可能也包含大廳聊天室或者好友之間的私聊，在這個情況下，接收訊息的對象就不適合使用 roomId 這類明指**遊戲房間**的名稱，所以才使用 to 作為 MessageType中，描述接收訊息對象的 key。當時其實還有其他選擇，像是 chatRoomId 或 chatRoomName 等等，如果有更好的看法，完全可以進行調整！


那假如是後者，不確定你的意思是否是將現行的
```
case SOCKET_EVENT.USER_JOINED:
            socket.emit(SOCKET_EVENT.USER_JOINED, {
              user: {
                id: "mock_user_id",
                nickname: "mock_user",
              },
              roomId: message.to,
            });
            break;
```
改回第一個 commit 的這樣呢？
```
case SOCKET_EVENT.USER_JOINED:
            socket.emit(SOCKET_EVENT.USER_JOINED, {
              user: {
                id: "mock_user_id",
                nickname: "mock_user",
              },
              roomId: '0',
            });
            break;
```
這樣子寫的話，邏輯上的結果是，「不論發送的對象在哪個遊戲房間，mock socket server 接到訊息後都會嘗試往 roomId 為 0 的房間發送訊息」，假如未來我們將 mock socket server 的功能做得更齊全時，依然勢必要將 roomId 的 value 調整成變數，否則在開發模式下，如果不是去 0 號房進行測試，可能會沒有效果，這就是個人將原本 "0" 字串改成變數 (message.to) 的原因。


至於第二點 socket?.on 的議題，我有考慮到啦～我把這段程式碼往前放了，請參考下圖
![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/114204927/236f5fe1-beff-44d7-b9e1-eb44f637f28d)
依現行的調整應該不會讓你的 VSCode 抱怨的，假如有抱怨的話，可以再找個時間讓我診斷一下～

以上說明，感謝！

2023-08-14 05:09 UTC, bxbdev commented
> Hello bxb,
> 
> 先說明一個前提是，依現行主線的程式碼，透過聊天室發送訊息時，其型別已事先定義於 `components/rooms/RoomChatroom/index.ts` 裡面了，如下圖所示: ![image](https://user-images.githubusercontent.com/114204927/260360882-b6ca2369-f994-4f12-8efa-74653a87188c.png) 因此在前端透過聊天室發送訊息時，後端接到的資料 (socket.on 的第二個參數，`pages/api/mock/socketio.ts` Line 40)，其實就是 MessageType，因此再回傳給前端時，可以透過 message.to 取得 MessageType 中 to 的屬性。
> 
> 所以，不確定你對於 message.to 的想法是針對 MessageType 中的 to 屬性，還是針對 mock socket server 的使用方法呢?
> 
> 假如是前者，那型別完全是可以進行調整的： 先前定義聊天訊息的型別（MessageType）時，針對接收訊息對象的 key 到底該如何命名我也思考了許久，之所以沒有選擇使用 roomId，是因為考慮未來聊天訊息可能不只發生在房間內，可能也包含大廳聊天室或者好友之間的私聊，在這個情況下，接收訊息的對象就不適合使用 roomId 這類明指**遊戲房間**的名稱，所以才使用 to 作為 MessageType中，描述接收訊息對象的 key。當時其實還有其他選擇，像是 chatRoomId 或 chatRoomName 等等，如果有更好的看法，完全可以進行調整！
> 
> 那假如是後者，不確定你的意思是否是將現行的
> 
> ```
> case SOCKET_EVENT.USER_JOINED:
>             socket.emit(SOCKET_EVENT.USER_JOINED, {
>               user: {
>                 id: "mock_user_id",
>                 nickname: "mock_user",
>               },
>               roomId: message.to,
>             });
>             break;
> ```
> 
> 改回第一個 commit 的這樣呢？
> 
> ```
> case SOCKET_EVENT.USER_JOINED:
>             socket.emit(SOCKET_EVENT.USER_JOINED, {
>               user: {
>                 id: "mock_user_id",
>                 nickname: "mock_user",
>               },
>               roomId: '0',
>             });
>             break;
> ```
> 
> 這樣子寫的話，邏輯上的結果是，「不論發送的對象在哪個遊戲房間，mock socket server 接到訊息後都會嘗試往 roomId 為 0 的房間發送訊息」，假如未來我們將 mock socket server 的功能做得更齊全時，依然勢必要將 roomId 的 value 調整成變數，否則在開發模式下，如果不是去 0 號房進行測試，可能會沒有效果，這就是個人將原本 "0" 字串改成變數 (message.to) 的原因。
> 
> 至於第二點 socket?.on 的議題，我有考慮到啦～我把這段程式碼往前放了，請參考下圖 ![image](https://user-images.githubusercontent.com/114204927/260362010-236f5fe1-beff-44d7-b9e1-eb44f637f28d.png) 依現行的調整應該不會讓你的 VSCode 抱怨的，假如有抱怨的話，可以再找個時間讓我診斷一下～
> 
> 以上說明，感謝！

Hi Yuwen,
哦！那個是 mock api 的，沒事！我以為是前端送給後端的資料型態，這樣我沒有什麼問題了。
我本來以為是送資料給 backend，想說backend不需要特別註明 message.to，只需要一個 roomId 就好。
上面的調整內容，我沒有任何問題了。

謝謝你的回答。

2023-08-14 07:18 UTC, ttpss930141011 requested changes

2023-08-14 07:18 UTC, ttpss930141011 commented on pages/api/mock/socketio.ts
>            isEmitting = false;
這邊剛好我有一個地方需要修正，這是我之前沒有發現的地方，我不小心把
```
 // avoid memory leak
        if (!isEmitting) {
          sendOnlineUsers = setInterval(
            // eslint-disable-next-line no-console
            () => console.log("Online users: ", onlineUsers),
            5000
          );
          isEmitting = true;
        }
```
放在這個 DISCONNECT 事件裡面，可以麻煩你幫我移到 39 行( CONNECT 事件) 的地方嗎？
謝謝！

2023-08-14 10:42 UTC, Yuwen-ctw commented on pages/api/mock/socketio.ts
>            isEmitting = false;
Hello Justin 改好囉。

2023-08-20 09:11 UTC, ttpss930141011 commented on pages/api/mock/socketio.ts
>            isEmitting = false;
謝謝！

2023-08-20 09:11 UTC, ttpss930141011 approved these changes

2023-08-20 09:54 UTC, merged