Feat/login page v2
Game-as-a-Service/Game-Lobby-Web pull request #384
Opened 2024-04-28 08:29 UTC by physicsSorcererKing

## Why need this change? / Root cause:

- New UI:
  - BoxFancy (Polymorphic Box with Gradient border)
  - ButtonV2 (Polymorphic Button implemented with BoxFancy)
  - IconV2 (New icons and changed default settings)

## Changes made:

- components/shared/BoxFancy
- components/shared/Button/v2
- components/shared/Icon/v2
- lib/types.ts
- pages/login.tsx
- public/images/v2
- tailwind.config.js

## Test Scope / Change impact:

-

## Issue

-

2024-04-29 01:41 UTC, physicsSorcererKing commented
Button V2 的 disabled 似乎沒做好效果，我有空再處理

2024-05-01 13:11 UTC, JohnsonMao requested changes
推薦您先看過 https://ithelp.ithome.com.tw/articles/10308018
這篇文章後，我相信您會有新的想法，
重構完我再來 Review

2024-05-01 13:11 UTC, JohnsonMao commented on components/shared/BoxFancy/BoxFancy.tsx
> +  ]);
這裡使用 useMemo 的原因是什麼？

2024-05-01 13:11 UTC, JohnsonMao commented on components/shared/Button/v2/Button.tsx
> +  );
這裡是不是錯誤使用了 useCallback，
推薦給您看一篇文章 https://ithelp.ithome.com.tw/articles/10308018
介紹的很讚，保證你有收穫，
後面的程式碼你看完這篇文章後，重構完我再來 Review

2024-05-01 15:45 UTC, physicsSorcererKing commented on components/shared/BoxFancy/BoxFancy.tsx
> +  ]);
useMemo 沒必要，也不是啥複雜計算

2024-05-01 16:53 UTC, physicsSorcererKing commented on components/shared/Button/v2/Button.tsx
> +  );
這我好像是照抄v1的，不過我不覺得有錯誤。看完文章後，沒甚麼特別的收穫。

我個人的開發習慣上，寫在Component裡面的物件包含function，
不管有沒有複雜計算我基本上都會包在useMemo或useCallback中。
要的是根據deps減少重複render的效果，
因為這些東西永遠不知道日後會不會需要傳到其他元件或是用在useEffect上，所以不包白不包，效能能差多少再說。

而如果說不應該使用這類hooks的場合，那就是當你完全沒需要依賴Component props時，這些東西就該寫在component外面。

當使用者傳入onClick沒包在useCallback裡，這邊的useCallback就白包了，但這是使用UI的人覺得不用也沒差，那通常也沒甚麼關係。

React官方似乎也覺得這玩意太無聊了，19版就不會看到它們了...

2024-05-03 14:24 UTC, JohnsonMao commented on components/shared/Button/v2/Button.tsx
> +  );
不過 React 19 還是會看到 useCallback 與 useMemo 吧，
useCallback 與 useMemo 是在 React Compiler 中優化的。

2024-05-03 14:26 UTC, JohnsonMao approved these changes
如果您很清楚統一使用 useCallback 與 useMemo 要付出的代價的話，也是可以的。

2024-05-03 14:28 UTC, merged