feat: cover
Game-as-a-Service/Game-Lobby-Web pull request #49
Opened 2023-05-16 16:21 UTC by bxbdev

feat: cover

2023-05-18 15:16 UTC, HongLinLiao approved these changes

2023-06-01 02:14 UTC, JohnsonMao requested changes
目前牽涉到 yarn.lock 變動，所以有點難合併

2023-06-01 02:14 UTC, JohnsonMao commented on shared/components/Cover/index.tsx
> +    <style jsx global>{`
第一次看到這個用法@@ 學習到了
不過 global style 會建議集中處理會比較好管理
以我們使用的 TailwindCSS 可以設定在 `tailwind.config.js`

```js
module.exports = {
  theme: {
    extend: {
      animation: {
        unblur: 'unblur 1s linear',
      },
      keyframes: {
        unblur: {
          'from': { filter: 'blur(20px)' },
          'to': { filter: 'blur(0)' },
        }
      }
    }
  }
}
```

參考: [TailwindCSS/animation](https://tailwindcss.com/docs/animation#customizing-your-theme)

2023-06-01 02:14 UTC, JohnsonMao commented on yarn.lock
通常如果分支沒有安裝額外的套件
這個**理論**上是不會變動
也就不會 commit 上來
不過現在大家也都還在嘗試~
相信之後會越來越好

2023-06-01 02:48 UTC, bxbdev commented on shared/components/Cover/index.tsx
> +    <style jsx global>{`
會寫css變數的話(var(--)，不一定要全部照搬Tailwind CSS的方式，可以採用global style的方式，反而會比較容易maintain。

2023-06-01 02:49 UTC, bxbdev commented on shared/components/Cover/index.tsx
> +  const [blurDataURL, setBlurDataURL] = useState(src);
因為要圖片載入的時使，如果要用blur方式載入，就需要用到base64，並且等完全載入之後，才會完全顯示圖片。
這招處理不好，所以已經拿掉了。

2023-06-01 03:19 UTC, closed without merging